name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -e ".[dev]"

      - name: Run unit tests (no network)
        run: |
          # Run only unit tests that don't require network access
          # Currently all tests in test_download.py are offline (URL parsing/translation)
          pytest tests/test_download.py tests/test_export.py -v --tb=short
        env:
          # Ensure no network access during tests
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"

      - name: Run type checking
        run: |
          mypy slidegeist/download.py slidegeist/cli.py --strict
